### ISSUE TITLE
Signup form doesn't display form errors

### ISSUE THREAD

**Issue by ab7289** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#243] opened 2019-11-27 02:16 UTC
When attempting to create my own user account (along with the one that was created for me), when I entered my credentials and clicked submit, I was redirected back to the signup page but none of the form fields displayed errors, so I had no idea what field it was failing on.

**Comment by mksavic** [comment] 2019-11-27 16:02
@ab7289 Were you using the same email address as the account that was already made for you?

**Comment by ab7289** [comment] 2019-11-27 16:34
uh yes I think so. Also I intentionally used a bad password, something like 'asdf' or like that.

**Comment by vmoros** [comment] 2019-11-27 19:21
Duplicate of #212, closing

**Closed by vmoros** 2019-11-27 19:21 UTC
