### ISSUE TITLE
Event filters get refreshed after submit

### ISSUE THREAD

**Issue by utkarshp21** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#231] opened 2019-11-26 21:04 UTC
## Description
On events page after selecting and submitting the filters, all the fields in  filter gets refreshed. Also a text should be shown if there are no events. 

![filter2](https://user-images.githubusercontent.com/38756289/69672557-5a8b2b00-1066-11ea-80f7-88b800fadbf4.gif)

## Expected Behavior
After selecting and submitting the filters, all the selected filter data should persist .

## Steps to Reproduce
1) Select events tab
2) Select event filters 
3) Submit the filters

**Comment by vmoros** [comment] 2019-12-02 02:38
Closing this issue because it's a duplicate of #200

**Closed by vmoros** 2019-12-02 02:38 UTC
